joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

rrbot_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - shoulder
    - upperarm
    - forearm

  constraints:
    goal_time: 0.5
    shoulder:
      goal:       0.01
      trajectory: 0.05
    upperarm:
      goal:       0.01
      trajectory: 0.05
    forearm:
      goal:       0.01
      trajectory: 0.05

  gains:
    shoulder: {p: 1.0,  i: 0.0, d: 0.0, i_clamp: 1}
    upperarm: {p: 1.0,  i: 0.0, d: 0.0, i_clamp: 1}
    forearm: {p: 1.0,  i: 0.0, d: 0.0, i_clamp: 1}

  velocity_ff:
    shoulder: 1.0
    upperarm: 1.0
    forearm: 1.0
